name: 🐛 Bug Report
description: File an issue about a bug.
title: "[BUG] "
labels: [bug]
assignees: [zmsn-2077]
body:
  - type: markdown
    attributes:
      value: |
        Please do your best to make the issue as easy to act on as possible, and only submit here if there is clearly a problem with OmniSafe (ask in [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) first if unsure).

  - type: checkboxes
    id: steps
    attributes:
      label: Required prerequisites
      description: Make sure you've completed the following steps before submitting your issue -- thank you!
      options:
        - label: I have read the documentation <https://omnisafe.readthedocs.io>.
          required: true
        - label: I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
          required: true
        - label: Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).
          required: false

  - type: input
    id: version
    attributes:
      label: |
        What version of OmniSafe are you using?
      value: |
        python3 -m pip show omnisafe
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System information
      value: |
        Describe the characteristic of your environment:

        - Describe how the library was installed (pip, conda, source, ...)
        - Python version
        - Versions of any other relevant libraries

        ```python
        import sys, omnisafe
        print(sys.version, sys.platform)
        print(omnisafe.__version__)
        ```
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problem description
      placeholder: |
        Provide a short description, state the expected behavior and what actually happens. Include
        relevant information like what version of OmniSafe you are using, what system you are on,
        and any useful commands / output.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Reproducible example code
      value: |
        <!-- The code should be minimal, have minimal external dependencies, and isolate the
        functions that cause breakage. Submit matched and complete snippets that can be easily
        run to diagnose the issue. -->

        The Python snippets:

        ```python

        ```

        Run the snippets with the following commands:

        ```bash

        ```

        Extra dependencies:

        ```text

        ```
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Traceback
      placeholder: |
        Put the Python traceback information here.

        Traceback (most recent call last):
          File ...
      render: pytb

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: |
        Provide a clear and concise description of what you expected to happen.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      placeholder: |
        Add any other context about the problem here. Screenshots may also be helpful.

        If you know or suspect the reason for this bug, paste the code lines and suggest modifications.
